export const countryList = [
	{ ISO: "004", country: "Afghanistan" },
	{ ISO: "008", country: "Albania" },
	{ ISO: "010", country: "Antarctica" },
	{ ISO: "012", country: "Algeria" },
	{ ISO: "016", country: "American Samoa" },
	{ ISO: "020", country: "Andorra" },
	{ ISO: "024", country: "Angola" },
	{ ISO: "028", country: "Antigua and Barbuda" },
	{ ISO: "031", country: "Azerbaijan" },
	{ ISO: "032", country: "Argentina" },
	{ ISO: "036", country: "Australia" },
	{ ISO: "040", country: "Austria" },
	{ ISO: "044", country: "Bahamas" },
	{ ISO: "048", country: "Bahrain" },
	{ ISO: "050", country: "Bangladesh" },
	{ ISO: "051", country: "Armenia" },
	{ ISO: "052", country: "Barbados" },
	{ ISO: "056", country: "Belgium" },
	{ ISO: "060", country: "Bermuda" },
	{ ISO: "064", country: "Bhutan" },
	{ ISO: "068", country: "Bolivia" },
	{ ISO: "070", country: "Bosnia and Herzegovina" },
	{ ISO: "072", country: "Botswana" },
	{ ISO: "074", country: "Bouvet Island" },
	{ ISO: "076", country: "Brazil" },
	{ ISO: "084", country: "Belize	Formerly British Honduras" },
	{ ISO: "086", country: "British Indian Ocean Territory" },
	{ ISO: "090", country: "Solomon Islands" },
	{ ISO: "092", country: "Virgin Islands" },
	{ ISO: "096", country: "Brunei Darussalam" },
	{ ISO: "100", country: "Bulgaria" },
	{ ISO: "104", country: "Myanmar	Formerly Burma" },
	{ ISO: "108", country: "Burundi" },
	{ ISO: "112", country: "Belarus	Formerly Byelorussian SSR" },
	{ ISO: "116", country: "Cambodia" },
	{ ISO: "120", country: "Cameroon" },
	{ ISO: "124", country: "Canada" },
	{ ISO: "132", country: "Cabo Verde	Formerly Cape Verde" },
	{ ISO: "136", country: "Cayman Islands" },
	{ ISO: "140", country: "Central African Republic" },
	{ ISO: "144", country: "Sri Lanka" },
	{ ISO: "148", country: "Chad" },
	{ ISO: "152", country: "Chile" },
	{ ISO: "156", country: "China" },
	{ ISO: "158", country: "Taiwan" },
	{ ISO: "162", country: "Christmas Island" },
	{ ISO: "166", country: "Cocos Islands" },
	{ ISO: "170", country: "Colombia" },
	{ ISO: "174", country: "Comoros" },
	{ ISO: "175", country: "Mayotte" },
	{ ISO: "178", country: "Congo" },
	{ ISO: "180", country: "Congo, Democratic Republic of the" },
	{ ISO: "184", country: "Cook Islands" },
	{ ISO: "188", country: "Costa Rica" },
	{ ISO: "191", country: "Croatia" },
	{ ISO: "192", country: "Cuba" },
	{ ISO: "196", country: "Cyprus" },
	{ ISO: "203", country: "Czechia" },
	{ ISO: "204", country: "Benin" },
	{ ISO: "208", country: "Denmark" },
	{ ISO: "212", country: "Dominica" },
	{ ISO: "214", country: "Dominican Republic" },
	{ ISO: "218", country: "Ecuador" },
	{ ISO: "222", country: "El Salvador" },
	{ ISO: "226", country: "Equatorial Guinea" },
	{ ISO: "231", country: "Ethiopia" },
	{ ISO: "232", country: "Eritrea" },
	{ ISO: "233", country: "Estonia" },
	{ ISO: "234", country: "Faroe Island" },
	{ ISO: "238", country: "Falkland Islands" },
	{ ISO: "239", country: "South Georgia and the South Sandwich Islands" },
	{ ISO: "242", country: "Fiji" },
	{ ISO: "246", country: "Finland" },
	{ ISO: "248", country: "Åland Islands" },
	{ ISO: "250", country: "France" },
	{ ISO: "254", country: "French Guiana" },
	{ ISO: "258", country: "French Polynesia" },
	{ ISO: "260", country: "French Southern Territories" },
	{ ISO: "262", country: "Djibouti" },
	{ ISO: "266", country: "Gabon" },
	{ ISO: "268", country: "Georgia" },
	{ ISO: "270", country: "Gambia" },
	{ ISO: "275", country: "Palestine" },
	{ ISO: "276", country: "Germany" },
	{ ISO: "288", country: "Ghana" },
	{ ISO: "292", country: "Gibraltar" },
	{ ISO: "296", country: "Kiribati" },
	{ ISO: "300", country: "Greece" },
	{ ISO: "304", country: "Greenland" },
	{ ISO: "308", country: "Grenada" },
	{ ISO: "312", country: "Guadeloupe" },
	{ ISO: "316", country: "Guam" },
	{ ISO: "320", country: "Guatemala" },
	{ ISO: "324", country: "Guinea" },
	{ ISO: "328", country: "Guyana" },
	{ ISO: "332", country: "Haiti" },
	{ ISO: "334", country: "Heard Island and McDonald Islands" },
	{ ISO: "336", country: "Holy See" },
	{ ISO: "340", country: "Honduras" },
	{ ISO: "344", country: "Hong Kong" },
	{ ISO: "348", country: "Hungary" },
	{ ISO: "352", country: "Iceland" },
	{ ISO: "356", country: "India" },
	{ ISO: "360", country: "Indonesia" },
	{ ISO: "364", country: "Iran" },
	{ ISO: "368", country: "Iraq" },
	{ ISO: "372", country: "Ireland" },
	{ ISO: "376", country: "Israel" },
	{ ISO: "380", country: "Italy" },
	{ ISO: "384", country: "Côte d'Ivoire" },
	{ ISO: "388", country: "Jamaica" },
	{ ISO: "392", country: "Japan" },
	{ ISO: "398", country: "Kazakhstan" },
	{ ISO: "400", country: "Jordan" },
	{ ISO: "404", country: "Kenya" },
	{ ISO: "408", country: "North Korea" },
	{ ISO: "410", country: "South Korea" },
	{ ISO: "414", country: "Kuwait" },
	{ ISO: "417", country: "Kyrgyzstan" },
	{ ISO: "418", country: "Lao People's Democratic Republic" },
	{ ISO: "422", country: "Lebanon" },
	{ ISO: "426", country: "Lesotho" },
	{ ISO: "428", country: "Latvia" },
	{ ISO: "430", country: "Liberia" },
	{ ISO: "434", country: "Libya" },
	{ ISO: "438", country: "Liechtenstein" },
	{ ISO: "440", country: "Lithuania" },
	{ ISO: "442", country: "Luxembourg" },
	{ ISO: "446", country: "Macao" },
	{ ISO: "450", country: "Madagascar" },
	{ ISO: "454", country: "Malawi" },
	{ ISO: "458", country: "Malaysia" },
	{ ISO: "462", country: "Maldives" },
	{ ISO: "466", country: "Mali" },
	{ ISO: "470", country: "Malta" },
	{ ISO: "474", country: "Martinique" },
	{ ISO: "478", country: "Mauritania" },
	{ ISO: "480", country: "Mauritius" },
	{ ISO: "484", country: "Mexico" },
	{ ISO: "492", country: "Monaco" },
	{ ISO: "496", country: "Mongolia" },
	{ ISO: "498", country: "Moldova" },
	{ ISO: "499", country: "Montenegro" },
	{ ISO: "500", country: "Montserrat" },
	{ ISO: "504", country: "Morocco" },
	{ ISO: "508", country: "Mozambique" },
	{ ISO: "512", country: "Oman" },
	{ ISO: "516", country: "Namibia" },
	{ ISO: "520", country: "Nauru" },
	{ ISO: "524", country: "Nepal" },
	{ ISO: "528", country: "Netherlands" },
	{ ISO: "531", country: "Curaçao" },
	{ ISO: "533", country: "Aruba" },
	{ ISO: "534", country: "Sint Maarten" },
	{ ISO: "535", country: "Bonaire, Sint Eustatius and Saba" },
	{ ISO: "540", country: "New Caledonia" },
	{ ISO: "548", country: "Vanuatu	Formerly New Hebrides" },
	{ ISO: "554", country: "New Zealand" },
	{ ISO: "558", country: "Nicaragua" },
	{ ISO: "562", country: "Niger" },
	{ ISO: "566", country: "Nigeria" },
	{ ISO: "570", country: "Niue" },
	{ ISO: "574", country: "Norfolk Island" },
	{ ISO: "578", country: "Norway" },
	{ ISO: "580", country: "Northern Mariana Islands" },
	{ ISO: "581", country: "United States Minor Outlying Island" },
	{ ISO: "583", country: "Micronesia" },
	{ ISO: "584", country: "Marshall Islands" },
	{ ISO: "585", country: "Palau Until" },
	{ ISO: "586", country: "Pakistan" },
	{ ISO: "591", country: "Panama" },
	{ ISO: "598", country: "Papua New Guinea" },
	{ ISO: "600", country: "Paraguay" },
	{ ISO: "604", country: "Peru" },
	{ ISO: "608", country: "Philippines" },
	{ ISO: "612", country: "Pitcairn" },
	{ ISO: "616", country: "Poland" },
	{ ISO: "620", country: "Portugal" },
	{ ISO: "624", country: "Guinea-Bissau" },
	{ ISO: "626", country: "Timor-Leste" },
	{ ISO: "630", country: "Puerto Rico" },
	{ ISO: "634", country: "Qatar" },
	{ ISO: "638", country: "Réunion" },
	{ ISO: "642", country: "Romania" },
	{ ISO: "643", country: "Russian Federation" },
	{ ISO: "646", country: "Rwanda" },
	{ ISO: "652", country: "Saint Barthélemy" },
	{ ISO: "654", country: "Saint Helena, Ascension and Tristan da Cunha" },
	{ ISO: "659", country: "Saint Kitts and Nevis" },
	{ ISO: "660", country: "Anguilla" },
	{ ISO: "662", country: "Saint Lucia" },
	{ ISO: "663", country: "Saint Martin" },
	{ ISO: "666", country: "Saint Pierre and Miquelon" },
	{ ISO: "670", country: "Saint Vincent and the Grenadines" },
	{ ISO: "674", country: "San Marino" },
	{ ISO: "678", country: "Sao Tome and Principe" },
	{ ISO: "682", country: "Saudi Arabia" },
	{ ISO: "686", country: "Senegal" },
	{ ISO: "688", country: "Serbia" },
	{ ISO: "690", country: "Seychelles" },
	{ ISO: "694", country: "Sierra Leone" },
	{ ISO: "702", country: "Singapore" },
	{ ISO: "703", country: "Slovakia" },
	{ ISO: "704", country: "Viet Nam" },
	{ ISO: "705", country: "Slovenia" },
	{ ISO: "706", country: "Somalia" },
	{ ISO: "710", country: "South Africa" },
	{ ISO: "716", country: "Zimbabwe" },
	{ ISO: "724", country: "Spain" },
	{ ISO: "728", country: "South Sudan" },
	{ ISO: "729", country: "Sudan" },
	{ ISO: "732", country: "Western Sahara" },
	{ ISO: "740", country: "Suriname" },
	{ ISO: "744", country: "Svalbard and Jan Mayen" },
	{ ISO: "748", country: "Eswatini" },
	{ ISO: "752", country: "Sweden" },
	{ ISO: "756", country: "Switzerland" },
	{ ISO: "760", country: "Syrian Arab Republic" },
	{ ISO: "762", country: "Tajikistan" },
	{ ISO: "764", country: "Thailand" },
	{ ISO: "768", country: "Togo" },
	{ ISO: "772", country: "Tokelau" },
	{ ISO: "776", country: "Tonga" },
	{ ISO: "780", country: "Trinidad and Tobago" },
	{ ISO: "784", country: "United Arab Emirates" },
	{ ISO: "788", country: "Tunisia" },
	{ ISO: "792", country: "Turkey" },
	{ ISO: "795", country: "Turkmenistan" },
	{ ISO: "796", country: "Turks and Caicos Islands" },
	{ ISO: "798", country: "Tuvalu" },
	{ ISO: "800", country: "Uganda" },
	{ ISO: "804", country: "Ukraine" },
	{ ISO: "807", country: "North Macedonia" },
	{ ISO: "818", country: "Egypt Formerly United Arab Republic" },
	{
		ISO: "826",
		country: "United Kingdom of Great Britain and Northern Ireland",
	},
	{ ISO: "831", country: "Guernsey" },
	{ ISO: "832", country: "Jersey	Until" },
	{ ISO: "833", country: "Isle of Man" },
	{ ISO: "834", country: "Tanzania," },
	{ ISO: "840", country: "United States of America" },
	{ ISO: "850", country: "Virgin Islands (US)" },
	{ ISO: "854", country: "Burkina Faso" },
	{ ISO: "858", country: "Uruguay" },
	{ ISO: "860", country: "Uzbekistan" },
	{ ISO: "862", country: "Venezuela" },
	{ ISO: "876", country: "Wallis and Futuna" },
	{ ISO: "882", country: "Samoa" },
	{ ISO: "887", country: "Yemen" },
	{ ISO: "894", country: "Zambia" },
];
