export const country_details = [
	{
		country: "Andorra",
		image: "https://flagcdn.com/96x72/ad.png",
		ISOcode: "ad",
		three_digit_ISO_country_code: "020",
	},
	{
		country: "United Arab Emirates",
		image: "https://flagcdn.com/96x72/ae.png",
		ISOcode: "ae",
		three_digit_ISO_country_code: "784",
	},
	{
		country: "Afghanistan",
		image: "https://flagcdn.com/96x72/af.png",
		ISOcode: "af",
		three_digit_ISO_country_code: "004",
	},
	{
		country: "Antigua and Barbuda",
		image: "https://flagcdn.com/96x72/ag.png",
		ISOcode: "ag",
		three_digit_ISO_country_code: "028",
	},
	{
		country: "Anguilla",
		image: "https://flagcdn.com/96x72/ai.png",
		ISOcode: "ai",
		three_digit_ISO_country_code: "660",
	},
	{
		country: "Albania",
		image: "https://flagcdn.com/96x72/al.png",
		ISOcode: "al",
		three_digit_ISO_country_code: "008",
	},
	{
		country: "Armenia",
		image: "https://flagcdn.com/96x72/am.png",
		ISOcode: "am",
		three_digit_ISO_country_code: "051",
	},
	{
		country: "Angola",
		image: "https://flagcdn.com/96x72/ao.png",
		ISOcode: "ao",
		three_digit_ISO_country_code: "024",
	},
	{
		country: "Antarctica",
		image: "https://flagcdn.com/96x72/aq.png",
		ISOcode: "aq",
		three_digit_ISO_country_code: "010",
	},
	{
		country: "Argentina",
		image: "https://flagcdn.com/96x72/ar.png",
		ISOcode: "ar",
		three_digit_ISO_country_code: "032",
	},
	{
		country: "American Samoa",
		image: "https://flagcdn.com/96x72/as.png",
		ISOcode: "as",
		three_digit_ISO_country_code: "016",
	},
	{
		country: "Austria",
		image: "https://flagcdn.com/96x72/at.png",
		ISOcode: "at",
		three_digit_ISO_country_code: "040",
	},
	{
		country: "Australia",
		image: "https://flagcdn.com/96x72/au.png",
		ISOcode: "au",
		three_digit_ISO_country_code: "036",
	},
	{
		country: "Aruba",
		image: "https://flagcdn.com/96x72/aw.png",
		ISOcode: "aw",
		three_digit_ISO_country_code: "533",
	},
	{
		country: "\u00c3\u0192\u00e2\u20ac\u00a6land Islands",
		image: "https://flagcdn.com/96x72/ax.png",
		ISOcode: "ax",
		three_digit_ISO_country_code: "234",
	},
	{
		country: "Azerbaijan",
		image: "https://flagcdn.com/96x72/az.png",
		ISOcode: "az",
		three_digit_ISO_country_code: "031",
	},
	{
		country: "Bosnia and Herzegovina",
		image: "https://flagcdn.com/96x72/ba.png",
		ISOcode: "ba",
		three_digit_ISO_country_code: "070",
	},
	{
		country: "Barbados",
		image: "https://flagcdn.com/96x72/bb.png",
		ISOcode: "bb",
		three_digit_ISO_country_code: "052",
	},
	{
		country: "Bangladesh",
		image: "https://flagcdn.com/96x72/bd.png",
		ISOcode: "bd",
		three_digit_ISO_country_code: "050",
	},
	{
		country: "Belgium",
		image: "https://flagcdn.com/96x72/be.png",
		ISOcode: "be",
		three_digit_ISO_country_code: "056",
	},
	{
		country: "Burkina Faso",
		image: "https://flagcdn.com/96x72/bf.png",
		ISOcode: "bf",
		three_digit_ISO_country_code: "854",
	},
	{
		country: "Bulgaria",
		image: "https://flagcdn.com/96x72/bg.png",
		ISOcode: "bg",
		three_digit_ISO_country_code: "100",
	},
	{
		country: "Bahrain",
		image: "https://flagcdn.com/96x72/bh.png",
		ISOcode: "bh",
		three_digit_ISO_country_code: "048",
	},
	{
		country: "Burundi",
		image: "https://flagcdn.com/96x72/bi.png",
		ISOcode: "bi",
		three_digit_ISO_country_code: "108",
	},
	{
		country: "Benin",
		image: "https://flagcdn.com/96x72/bj.png",
		ISOcode: "bj",
		three_digit_ISO_country_code: "204",
	},
	{
		country: "Saint Barth\u00c3\u0192\u00c2\u00a9lemy",
		image: "https://flagcdn.com/96x72/bl.png",
		ISOcode: "bl",
		three_digit_ISO_country_code: "652",
	},
	{
		country: "Bermuda",
		image: "https://flagcdn.com/96x72/bm.png",
		ISOcode: "bm",
		three_digit_ISO_country_code: "060",
	},
	{
		country: "Brunei",
		image: "https://flagcdn.com/96x72/bn.png",
		ISOcode: "bn",
		three_digit_ISO_country_code: "096",
	},
	{
		country: "Bolivia",
		image: "https://flagcdn.com/96x72/bo.png",
		ISOcode: "bo",
		three_digit_ISO_country_code: "068",
	},
	{
		country: "Caribbean Netherlands",
		image: "https://flagcdn.com/96x72/bq.png",
		ISOcode: "bq",
		three_digit_ISO_country_code: "535",
	},
	{
		country: "Brazil",
		image: "https://flagcdn.com/96x72/br.png",
		ISOcode: "br",
		three_digit_ISO_country_code: "076",
	},
	{
		country: "Bahamas",
		image: "https://flagcdn.com/96x72/bs.png",
		ISOcode: "bs",
		three_digit_ISO_country_code: "044",
	},
	{
		country: "Bhutan",
		image: "https://flagcdn.com/96x72/bt.png",
		ISOcode: "bt",
		three_digit_ISO_country_code: "064",
	},
	{
		country: "Bouvet Island",
		image: "https://flagcdn.com/96x72/bv.png",
		ISOcode: "bv",
		three_digit_ISO_country_code: "074",
	},
	{
		country: "Botswana",
		image: "https://flagcdn.com/96x72/bw.png",
		ISOcode: "bw",
		three_digit_ISO_country_code: "072",
	},
	{
		country: "Belarus",
		image: "https://flagcdn.com/96x72/by.png",
		ISOcode: "by",
		three_digit_ISO_country_code: "112",
	},
	{
		country: "Belize",
		image: "https://flagcdn.com/96x72/bz.png",
		ISOcode: "bz",
		three_digit_ISO_country_code: "084",
	},
	{
		country: "Canada",
		image: "https://flagcdn.com/96x72/ca.png",
		ISOcode: "ca",
		three_digit_ISO_country_code: "124",
	},
	{
		country: "Cocos (Keeling) Islands",
		image: "https://flagcdn.com/96x72/cc.png",
		ISOcode: "cc",
		three_digit_ISO_country_code: "166",
	},
	{
		country: "DR Congo",
		image: "https://flagcdn.com/96x72/cd.png",
		ISOcode: "cd",
		three_digit_ISO_country_code: "178",
	},
	{
		country: "Central African Republic",
		image: "https://flagcdn.com/96x72/cf.png",
		ISOcode: "cf",
		three_digit_ISO_country_code: "140",
	},
	{
		country: "Republic of the Congo",
		image: "https://flagcdn.com/96x72/cg.png",
		ISOcode: "cg",
		three_digit_ISO_country_code: "180",
	},
	{
		country: "Switzerland",
		image: "https://flagcdn.com/96x72/ch.png",
		ISOcode: "ch",
		three_digit_ISO_country_code: "756",
	},
	{
		country: "Ivory Coast",
		image: "https://flagcdn.com/96x72/ci.png",
		ISOcode: "ci",
		three_digit_ISO_country_code: "384",
	},
	{
		country: "Cook Islands",
		image: "https://flagcdn.com/96x72/ck.png",
		ISOcode: "ck",
		three_digit_ISO_country_code: "184",
	},
	{
		country: "Chile",
		image: "https://flagcdn.com/96x72/cl.png",
		ISOcode: "cl",
		three_digit_ISO_country_code: "152",
	},
	{
		country: "Cameroon",
		image: "https://flagcdn.com/96x72/cm.png",
		ISOcode: "cm",
		three_digit_ISO_country_code: "120",
	},
	{
		country: "China",
		image: "https://flagcdn.com/96x72/cn.png",
		ISOcode: "cn",
		three_digit_ISO_country_code: "156",
	},
	{
		country: "Colombia",
		image: "https://flagcdn.com/96x72/co.png",
		ISOcode: "co",
		three_digit_ISO_country_code: "170",
	},
	{
		country: "Costa Rica",
		image: "https://flagcdn.com/96x72/cr.png",
		ISOcode: "cr",
		three_digit_ISO_country_code: "188",
	},
	{
		country: "Cuba",
		image: "https://flagcdn.com/96x72/cu.png",
		ISOcode: "cu",
		three_digit_ISO_country_code: "192",
	},
	{
		country: "Cape Verde",
		image: "https://flagcdn.com/96x72/cv.png",
		ISOcode: "cv",
		three_digit_ISO_country_code: "132",
	},
	{
		country: "Cura\u00c3\u0192\u00c2\u00a7ao",
		image: "https://flagcdn.com/96x72/cw.png",
		ISOcode: "cw",
		three_digit_ISO_country_code: "531",
	},
	{
		country: "Christmas Island",
		image: "https://flagcdn.com/96x72/cx.png",
		ISOcode: "cx",
		three_digit_ISO_country_code: "162",
	},
	{
		country: "Cyprus",
		image: "https://flagcdn.com/96x72/cy.png",
		ISOcode: "cy",
		three_digit_ISO_country_code: "196",
	},
	{
		country: "Czechia",
		image: "https://flagcdn.com/96x72/cz.png",
		ISOcode: "cz",
		three_digit_ISO_country_code: "203",
	},
	{
		country: "Germany",
		image: "https://flagcdn.com/96x72/de.png",
		ISOcode: "de",
		three_digit_ISO_country_code: "276",
	},
	{
		country: "Djibouti",
		image: "https://flagcdn.com/96x72/dj.png",
		ISOcode: "dj",
		three_digit_ISO_country_code: "262",
	},
	{
		country: "Denmark",
		image: "https://flagcdn.com/96x72/dk.png",
		ISOcode: "dk",
		three_digit_ISO_country_code: "208",
	},
	{
		country: "Dominica",
		image: "https://flagcdn.com/96x72/dm.png",
		ISOcode: "dm",
		three_digit_ISO_country_code: "212",
	},
	{
		country: "Dominican Republic",
		image: "https://flagcdn.com/96x72/do.png",
		ISOcode: "do",
		three_digit_ISO_country_code: "214",
	},
	{
		country: "Algeria",
		image: "https://flagcdn.com/96x72/dz.png",
		ISOcode: "dz",
		three_digit_ISO_country_code: "012",
	},
	{
		country: "Ecuador",
		image: "https://flagcdn.com/96x72/ec.png",
		ISOcode: "ec",
		three_digit_ISO_country_code: "218",
	},
	{
		country: "Estonia",
		image: "https://flagcdn.com/96x72/ee.png",
		ISOcode: "ee",
		three_digit_ISO_country_code: "233",
	},
	{
		country: "Egypt",
		image: "https://flagcdn.com/96x72/eg.png",
		ISOcode: "eg",
		three_digit_ISO_country_code: "818",
	},
	{
		country: "Western Sahara",
		image: "https://flagcdn.com/96x72/eh.png",
		ISOcode: "eh",
		three_digit_ISO_country_code: "732",
	},
	{
		country: "Eritrea",
		image: "https://flagcdn.com/96x72/er.png",
		ISOcode: "er",
		three_digit_ISO_country_code: "232",
	},
	{
		country: "Spain",
		image: "https://flagcdn.com/96x72/es.png",
		ISOcode: "es",
		three_digit_ISO_country_code: "724",
	},
	{
		country: "Ethiopia",
		image: "https://flagcdn.com/96x72/et.png",
		ISOcode: "et",
		three_digit_ISO_country_code: "231",
	},
	{
		country: "European Union",
		image: "https://flagcdn.com/96x72/eu.png",
		ISOcode: "eu",
	},
	{
		country: "Finland",
		image: "https://flagcdn.com/96x72/fi.png",
		ISOcode: "fi",
		three_digit_ISO_country_code: "246",
	},
	{
		country: "Fiji",
		image: "https://flagcdn.com/96x72/fj.png",
		ISOcode: "fj",
		three_digit_ISO_country_code: "242",
	},
	{
		country: "Falkland Islands",
		image: "https://flagcdn.com/96x72/fk.png",
		ISOcode: "fk",
		three_digit_ISO_country_code: "238",
	},
	{
		country: "Micronesia",
		image: "https://flagcdn.com/96x72/fm.png",
		ISOcode: "fm",
		three_digit_ISO_country_code: "583",
	},
	{
		country: "Faroe Islands",
		image: "https://flagcdn.com/96x72/fo.png",
		ISOcode: "fo",
		three_digit_ISO_country_code: "234",
	},
	{
		country: "France",
		image: "https://flagcdn.com/96x72/fr.png",
		ISOcode: "fr",
		three_digit_ISO_country_code: "250",
	},
	{
		country: "Gabon",
		image: "https://flagcdn.com/96x72/ga.png",
		ISOcode: "ga",
		three_digit_ISO_country_code: "266",
	},
	{
		country: "United Kingdom",
		image: "https://flagcdn.com/96x72/gb.png",
		ISOcode: "gb",
		three_digit_ISO_country_code: "826",
	},
	{
		country: "England",
		image: "https://flagcdn.com/96x72/gb-eng.png",
		ISOcode: "gb-eng",
		three_digit_ISO_country_code: "826",
	},
	{
		country: "Northern Ireland",
		image: "https://flagcdn.com/96x72/gb-nir.png",
		ISOcode: "gb-nir",
		three_digit_ISO_country_code: "826",
	},
	{
		country: "Scotland",
		image: "https://flagcdn.com/96x72/gb-sct.png",
		ISOcode: "gb-sct",
		three_digit_ISO_country_code: "826",
	},
	{
		country: "Wales",
		image: "https://flagcdn.com/96x72/gb-wls.png",
		ISOcode: "gb-wls",
		three_digit_ISO_country_code: "826",
	},
	{
		country: "Grenada",
		image: "https://flagcdn.com/96x72/gd.png",
		ISOcode: "gd",
		three_digit_ISO_country_code: "308",
	},
	{
		country: "Georgia",
		image: "https://flagcdn.com/96x72/ge.png",
		ISOcode: "ge",
		three_digit_ISO_country_code: "268",
	},
	{
		country: "French Guiana",
		image: "https://flagcdn.com/96x72/gf.png",
		ISOcode: "gf",
		three_digit_ISO_country_code: "254",
	},
	{
		country: "Guernsey",
		image: "https://flagcdn.com/96x72/gg.png",
		ISOcode: "gg",
		three_digit_ISO_country_code: "831",
	},
	{
		country: "Ghana",
		image: "https://flagcdn.com/96x72/gh.png",
		ISOcode: "gh",
		three_digit_ISO_country_code: "288",
	},
	{
		country: "Gibraltar",
		image: "https://flagcdn.com/96x72/gi.png",
		ISOcode: "gi",
		three_digit_ISO_country_code: "292",
	},
	{
		country: "Greenland",
		image: "https://flagcdn.com/96x72/gl.png",
		ISOcode: "gl",
		three_digit_ISO_country_code: "304",
	},
	{
		country: "Gambia",
		image: "https://flagcdn.com/96x72/gm.png",
		ISOcode: "gm",
		three_digit_ISO_country_code: "270",
	},
	{
		country: "Guinea",
		image: "https://flagcdn.com/96x72/gn.png",
		ISOcode: "gn",
		three_digit_ISO_country_code: "324",
	},
	{
		country: "Guadeloupe",
		image: "https://flagcdn.com/96x72/gp.png",
		ISOcode: "gp",
		three_digit_ISO_country_code: "312",
	},
	{
		country: "Equatorial Guinea",
		image: "https://flagcdn.com/96x72/gq.png",
		ISOcode: "gq",
		three_digit_ISO_country_code: "226",
	},
	{
		country: "Greece",
		image: "https://flagcdn.com/96x72/gr.png",
		ISOcode: "gr",
		three_digit_ISO_country_code: "300",
	},
	{
		country: "South Georgia",
		image: "https://flagcdn.com/96x72/gs.png",
		ISOcode: "gs",
		three_digit_ISO_country_code: "239",
	},
	{
		country: "Guatemala",
		image: "https://flagcdn.com/96x72/gt.png",
		ISOcode: "gt",
		three_digit_ISO_country_code: "320",
	},
	{
		country: "Guam",
		image: "https://flagcdn.com/96x72/gu.png",
		ISOcode: "gu",
		three_digit_ISO_country_code: "316",
	},
	{
		country: "Guinea-Bissau",
		image: "https://flagcdn.com/96x72/gw.png",
		ISOcode: "gw",
		three_digit_ISO_country_code: "624",
	},
	{
		country: "Guyana",
		image: "https://flagcdn.com/96x72/gy.png",
		ISOcode: "gy",
		three_digit_ISO_country_code: "328",
	},
	{
		country: "Hong Kong",
		image: "https://flagcdn.com/96x72/hk.png",
		ISOcode: "hk",
		three_digit_ISO_country_code: "344",
	},
	{
		country: "Heard Island and McDonald Islands",
		image: "https://flagcdn.com/96x72/hm.png",
		ISOcode: "hm",
		three_digit_ISO_country_code: "334",
	},
	{
		country: "Honduras",
		image: "https://flagcdn.com/96x72/hn.png",
		ISOcode: "hn",
		three_digit_ISO_country_code: "340",
	},
	{
		country: "Croatia",
		image: "https://flagcdn.com/96x72/hr.png",
		ISOcode: "hr",
		three_digit_ISO_country_code: "191",
	},
	{
		country: "Haiti",
		image: "https://flagcdn.com/96x72/ht.png",
		ISOcode: "ht",
		three_digit_ISO_country_code: "332",
	},
	{
		country: "Hungary",
		image: "https://flagcdn.com/96x72/hu.png",
		ISOcode: "hu",
		three_digit_ISO_country_code: "348",
	},
	{
		country: "Indonesia",
		image: "https://flagcdn.com/96x72/id.png",
		ISOcode: "id",
		three_digit_ISO_country_code: "360",
	},
	{
		country: "Ireland",
		image: "https://flagcdn.com/96x72/ie.png",
		ISOcode: "ie",
		three_digit_ISO_country_code: "372",
	},
	{
		country: "Israel",
		image: "https://flagcdn.com/96x72/il.png",
		ISOcode: "il",
		three_digit_ISO_country_code: "376",
	},
	{
		country: "Isle of Man",
		image: "https://flagcdn.com/96x72/im.png",
		ISOcode: "im",
		three_digit_ISO_country_code: "833",
	},
	{
		country: "India",
		image: "https://flagcdn.com/96x72/in.png",
		ISOcode: "in",
		three_digit_ISO_country_code: "356",
	},
	{
		country: "British Indian Ocean Territory",
		image: "https://flagcdn.com/96x72/io.png",
		ISOcode: "io",
		three_digit_ISO_country_code: "086",
	},
	{
		country: "Iraq",
		image: "https://flagcdn.com/96x72/iq.png",
		ISOcode: "iq",
		three_digit_ISO_country_code: "368",
	},
	{
		country: "Iran",
		image: "https://flagcdn.com/96x72/ir.png",
		ISOcode: "ir",
		three_digit_ISO_country_code: "364",
	},
	{
		country: "Iceland",
		image: "https://flagcdn.com/96x72/is.png",
		ISOcode: "is",
		three_digit_ISO_country_code: "352",
	},
	{
		country: "Italy",
		image: "https://flagcdn.com/96x72/it.png",
		ISOcode: "it",
		three_digit_ISO_country_code: "380",
	},
	{
		country: "Jersey",
		image: "https://flagcdn.com/96x72/je.png",
		ISOcode: "je",
		three_digit_ISO_country_code: "832",
	},
	{
		country: "Jamaica",
		image: "https://flagcdn.com/96x72/jm.png",
		ISOcode: "jm",
		three_digit_ISO_country_code: "388",
	},
	{
		country: "Jordan",
		image: "https://flagcdn.com/96x72/jo.png",
		ISOcode: "jo",
		three_digit_ISO_country_code: "400",
	},
	{
		country: "Japan",
		image: "https://flagcdn.com/96x72/jp.png",
		ISOcode: "jp",
		three_digit_ISO_country_code: "392",
	},
	{
		country: "Kenya",
		image: "https://flagcdn.com/96x72/ke.png",
		ISOcode: "ke",
		three_digit_ISO_country_code: "404",
	},
	{
		country: "Kyrgyzstan",
		image: "https://flagcdn.com/96x72/kg.png",
		ISOcode: "kg",
		three_digit_ISO_country_code: "417",
	},
	{
		country: "Cambodia",
		image: "https://flagcdn.com/96x72/kh.png",
		ISOcode: "kh",
		three_digit_ISO_country_code: "116",
	},
	{
		country: "Kiribati",
		image: "https://flagcdn.com/96x72/ki.png",
		ISOcode: "ki",
		three_digit_ISO_country_code: "296",
	},
	{
		country: "Comoros",
		image: "https://flagcdn.com/96x72/km.png",
		ISOcode: "km",
		three_digit_ISO_country_code: "174",
	},
	{
		country: "Saint Kitts and Nevis",
		image: "https://flagcdn.com/96x72/kn.png",
		ISOcode: "kn",
		three_digit_ISO_country_code: "659",
	},
	{
		country: "North Korea",
		image: "https://flagcdn.com/96x72/kp.png",
		ISOcode: "kp",
		three_digit_ISO_country_code: "408",
	},
	{
		country: "South Korea",
		image: "https://flagcdn.com/96x72/kr.png",
		ISOcode: "kr",
		three_digit_ISO_country_code: "410",
	},
	{
		country: "Kuwait",
		image: "https://flagcdn.com/96x72/kw.png",
		ISOcode: "kw",
		three_digit_ISO_country_code: "414",
	},
	{
		country: "Cayman Islands",
		image: "https://flagcdn.com/96x72/ky.png",
		ISOcode: "ky",
		three_digit_ISO_country_code: "136",
	},
	{
		country: "Kazakhstan",
		image: "https://flagcdn.com/96x72/kz.png",
		ISOcode: "kz",
		three_digit_ISO_country_code: "398",
	},
	{
		country: "Laos",
		image: "https://flagcdn.com/96x72/la.png",
		ISOcode: "la",
		three_digit_ISO_country_code: "418",
	},
	{
		country: "Lebanon",
		image: "https://flagcdn.com/96x72/lb.png",
		ISOcode: "lb",
		three_digit_ISO_country_code: "422",
	},
	{
		country: "Saint Lucia",
		image: "https://flagcdn.com/96x72/lc.png",
		ISOcode: "lc",
		three_digit_ISO_country_code: "662",
	},
	{
		country: "Liechtenstein",
		image: "https://flagcdn.com/96x72/li.png",
		ISOcode: "li",
		three_digit_ISO_country_code: "438",
	},
	{
		country: "Sri Lanka",
		image: "https://flagcdn.com/96x72/lk.png",
		ISOcode: "lk",
		three_digit_ISO_country_code: "144",
	},
	{
		country: "Liberia",
		image: "https://flagcdn.com/96x72/lr.png",
		ISOcode: "lr",
		three_digit_ISO_country_code: "430",
	},
	{
		country: "Lesotho",
		image: "https://flagcdn.com/96x72/ls.png",
		ISOcode: "ls",
		three_digit_ISO_country_code: "426",
	},
	{
		country: "Lithuania",
		image: "https://flagcdn.com/96x72/lt.png",
		ISOcode: "lt",
		three_digit_ISO_country_code: "440",
	},
	{
		country: "Luxembourg",
		image: "https://flagcdn.com/96x72/lu.png",
		ISOcode: "lu",
		three_digit_ISO_country_code: "442",
	},
	{
		country: "Latvia",
		image: "https://flagcdn.com/96x72/lv.png",
		ISOcode: "lv",
		three_digit_ISO_country_code: "428",
	},
	{
		country: "Libya",
		image: "https://flagcdn.com/96x72/ly.png",
		ISOcode: "ly",
		three_digit_ISO_country_code: "434",
	},
	{
		country: "Morocco",
		image: "https://flagcdn.com/96x72/ma.png",
		ISOcode: "ma",
		three_digit_ISO_country_code: "504",
	},
	{
		country: "Monaco",
		image: "https://flagcdn.com/96x72/mc.png",
		ISOcode: "mc",
		three_digit_ISO_country_code: "492",
	},
	{
		country: "Moldova",
		image: "https://flagcdn.com/96x72/md.png",
		ISOcode: "md",
		three_digit_ISO_country_code: "498",
	},
	{
		country: "Montenegro",
		image: "https://flagcdn.com/96x72/me.png",
		ISOcode: "me",
		three_digit_ISO_country_code: "499",
	},
	{
		country: "Saint Martin",
		image: "https://flagcdn.com/96x72/mf.png",
		ISOcode: "mf",
		three_digit_ISO_country_code: "663",
	},
	{
		country: "Madagascar",
		image: "https://flagcdn.com/96x72/mg.png",
		ISOcode: "mg",
		three_digit_ISO_country_code: "450",
	},
	{
		country: "Marshall Islands",
		image: "https://flagcdn.com/96x72/mh.png",
		ISOcode: "mh",
		three_digit_ISO_country_code: "584",
	},
	{
		country: "North Macedonia",
		image: "https://flagcdn.com/96x72/mk.png",
		ISOcode: "mk",
		three_digit_ISO_country_code: "807",
	},
	{
		country: "Mali",
		image: "https://flagcdn.com/96x72/ml.png",
		ISOcode: "ml",
		three_digit_ISO_country_code: "466",
	},
	{
		country: "Myanmar",
		image: "https://flagcdn.com/96x72/mm.png",
		ISOcode: "mm",
		three_digit_ISO_country_code: "104",
	},
	{
		country: "Mongolia",
		image: "https://flagcdn.com/96x72/mn.png",
		ISOcode: "mn",
		three_digit_ISO_country_code: "496",
	},
	{
		country: "Macau",
		image: "https://flagcdn.com/96x72/mo.png",
		ISOcode: "mo",
		three_digit_ISO_country_code: "446",
	},
	{
		country: "Northern Mariana Islands",
		image: "https://flagcdn.com/96x72/mp.png",
		ISOcode: "mp",
		three_digit_ISO_country_code: "580",
	},
	{
		country: "Martinique",
		image: "https://flagcdn.com/96x72/mq.png",
		ISOcode: "mq",
		three_digit_ISO_country_code: "474",
	},
	{
		country: "Mauritania",
		image: "https://flagcdn.com/96x72/mr.png",
		ISOcode: "mr",
		three_digit_ISO_country_code: "478",
	},
	{
		country: "Montserrat",
		image: "https://flagcdn.com/96x72/ms.png",
		ISOcode: "ms",
		three_digit_ISO_country_code: "500",
	},
	{
		country: "Malta",
		image: "https://flagcdn.com/96x72/mt.png",
		ISOcode: "mt",
		three_digit_ISO_country_code: "470",
	},
	{
		country: "Mauritius",
		image: "https://flagcdn.com/96x72/mu.png",
		ISOcode: "mu",
		three_digit_ISO_country_code: "480",
	},
	{
		country: "Maldives",
		image: "https://flagcdn.com/96x72/mv.png",
		ISOcode: "mv",
		three_digit_ISO_country_code: "462",
	},
	{
		country: "Malawi",
		image: "https://flagcdn.com/96x72/mw.png",
		ISOcode: "mw",
		three_digit_ISO_country_code: "454",
	},
	{
		country: "Mexico",
		image: "https://flagcdn.com/96x72/mx.png",
		ISOcode: "mx",
		three_digit_ISO_country_code: "484",
	},
	{
		country: "Malaysia",
		image: "https://flagcdn.com/96x72/my.png",
		ISOcode: "my",
		three_digit_ISO_country_code: "458",
	},
	{
		country: "Mozambique",
		image: "https://flagcdn.com/96x72/mz.png",
		ISOcode: "mz",
		three_digit_ISO_country_code: "508",
	},
	{
		country: "Namibia",
		image: "https://flagcdn.com/96x72/na.png",
		ISOcode: "na",
		three_digit_ISO_country_code: "516",
	},
	{
		country: "New Caledonia",
		image: "https://flagcdn.com/96x72/nc.png",
		ISOcode: "nc",
		three_digit_ISO_country_code: "540",
	},
	{
		country: "Niger",
		image: "https://flagcdn.com/96x72/ne.png",
		ISOcode: "ne",
		three_digit_ISO_country_code: "562",
	},
	{
		country: "Norfolk Island",
		image: "https://flagcdn.com/96x72/nf.png",
		ISOcode: "nf",
		three_digit_ISO_country_code: "574",
	},
	{
		country: "Nigeria",
		image: "https://flagcdn.com/96x72/ng.png",
		ISOcode: "ng",
		three_digit_ISO_country_code: "566",
	},
	{
		country: "Nicaragua",
		image: "https://flagcdn.com/96x72/ni.png",
		ISOcode: "ni",
		three_digit_ISO_country_code: "558",
	},
	{
		country: "Netherlands",
		image: "https://flagcdn.com/96x72/nl.png",
		ISOcode: "nl",
		three_digit_ISO_country_code: "528",
	},
	{
		country: "Norway",
		image: "https://flagcdn.com/96x72/no.png",
		ISOcode: "no",
		three_digit_ISO_country_code: "578",
	},
	{
		country: "Nepal",
		image: "https://flagcdn.com/96x72/np.png",
		ISOcode: "np",
		three_digit_ISO_country_code: "524",
	},
	{
		country: "Nauru",
		image: "https://flagcdn.com/96x72/nr.png",
		ISOcode: "nr",
		three_digit_ISO_country_code: "520",
	},
	{
		country: "Niue",
		image: "https://flagcdn.com/96x72/nu.png",
		ISOcode: "nu",
		three_digit_ISO_country_code: "570",
	},
	{
		country: "New Zealand",
		image: "https://flagcdn.com/96x72/nz.png",
		ISOcode: "nz",
		three_digit_ISO_country_code: "554",
	},
	{
		country: "Oman",
		image: "https://flagcdn.com/96x72/om.png",
		ISOcode: "om",
		three_digit_ISO_country_code: "512",
	},
	{
		country: "Panama",
		image: "https://flagcdn.com/96x72/pa.png",
		ISOcode: "pa",
		three_digit_ISO_country_code: "591",
	},
	{
		country: "Peru",
		image: "https://flagcdn.com/96x72/pe.png",
		ISOcode: "pe",
		three_digit_ISO_country_code: "604",
	},
	{
		country: "French Polynesia",
		image: "https://flagcdn.com/96x72/pf.png",
		ISOcode: "pf",
		three_digit_ISO_country_code: "258",
	},
	{
		country: "Papua New Guinea",
		image: "https://flagcdn.com/96x72/pg.png",
		ISOcode: "pg",
		three_digit_ISO_country_code: "598",
	},
	{
		country: "Philippines",
		image: "https://flagcdn.com/96x72/ph.png",
		ISOcode: "ph",
		three_digit_ISO_country_code: "608",
	},
	{
		country: "Pakistan",
		image: "https://flagcdn.com/96x72/pk.png",
		ISOcode: "pk",
		three_digit_ISO_country_code: "586",
	},
	{
		country: "Poland",
		image: "https://flagcdn.com/96x72/pl.png",
		ISOcode: "pl",
		three_digit_ISO_country_code: "616",
	},
	{
		country: "Saint Pierre and Miquelon",
		image: "https://flagcdn.com/96x72/pm.png",
		ISOcode: "pm",
		three_digit_ISO_country_code: "666",
	},
	{
		country: "Pitcairn Islands",
		image: "https://flagcdn.com/96x72/pn.png",
		ISOcode: "pn",
		three_digit_ISO_country_code: "612",
	},
	{
		country: "Puerto Rico",
		image: "https://flagcdn.com/96x72/pr.png",
		ISOcode: "pr",
		three_digit_ISO_country_code: "630",
	},
	{
		country: "Palestine",
		image: "https://flagcdn.com/96x72/ps.png",
		ISOcode: "ps",
		three_digit_ISO_country_code: "275",
	},
	{
		country: "Portugal",
		image: "https://flagcdn.com/96x72/pt.png",
		ISOcode: "pt",
		three_digit_ISO_country_code: "620",
	},
	{
		country: "Palau",
		image: "https://flagcdn.com/96x72/pw.png",
		ISOcode: "pw",
		three_digit_ISO_country_code: "585",
	},
	{
		country: "Paraguay",
		image: "https://flagcdn.com/96x72/py.png",
		ISOcode: "py",
		three_digit_ISO_country_code: "600",
	},
	{
		country: "Qatar",
		image: "https://flagcdn.com/96x72/qa.png",
		ISOcode: "qa",
		three_digit_ISO_country_code: "634",
	},
	{
		country: "R\u00c3\u0192\u00c2\u00a9union",
		image: "https://flagcdn.com/96x72/re.png",
		ISOcode: "re",
		three_digit_ISO_country_code: "638",
	},
	{
		country: "Romania",
		image: "https://flagcdn.com/96x72/ro.png",
		ISOcode: "ro",
		three_digit_ISO_country_code: "642",
	},
	{
		country: "Serbia",
		image: "https://flagcdn.com/96x72/rs.png",
		ISOcode: "rs",
		three_digit_ISO_country_code: "688",
	},
	{
		country: "Russia",
		image: "https://flagcdn.com/96x72/ru.png",
		ISOcode: "ru",
		three_digit_ISO_country_code: "643",
	},
	{
		country: "Rwanda",
		image: "https://flagcdn.com/96x72/rw.png",
		ISOcode: "rw",
		three_digit_ISO_country_code: "646",
	},
	{
		country: "Saudi Arabia",
		image: "https://flagcdn.com/96x72/sa.png",
		ISOcode: "sa",
		three_digit_ISO_country_code: "682",
	},
	{
		country: "Solomon Islands",
		image: "https://flagcdn.com/96x72/sb.png",
		ISOcode: "sb",
		three_digit_ISO_country_code: "090",
	},
	{
		country: "Seychelles",
		image: "https://flagcdn.com/96x72/sc.png",
		ISOcode: "sc",
		three_digit_ISO_country_code: "690",
	},
	{
		country: "Sudan",
		image: "https://flagcdn.com/96x72/sd.png",
		ISOcode: "sd",
		three_digit_ISO_country_code: "729",
	},
	{
		country: "Sweden",
		image: "https://flagcdn.com/96x72/se.png",
		ISOcode: "se",
		three_digit_ISO_country_code: "752",
	},
	{
		country: "Singapore",
		image: "https://flagcdn.com/96x72/sg.png",
		ISOcode: "sg",
		three_digit_ISO_country_code: "702",
	},
	{
		country: "Saint Helena, Ascension and Tristan da Cunha",
		image: "https://flagcdn.com/96x72/sh.png",
		ISOcode: "sh",
		three_digit_ISO_country_code: "654",
	},
	{
		country: "Slovenia",
		image: "https://flagcdn.com/96x72/si.png",
		ISOcode: "si",
		three_digit_ISO_country_code: "705",
	},
	{
		country: "Svalbard and Jan Mayen",
		image: "https://flagcdn.com/96x72/sj.png",
		ISOcode: "sj",
		three_digit_ISO_country_code: "744",
	},
	{
		country: "Slovakia",
		image: "https://flagcdn.com/96x72/sk.png",
		ISOcode: "sk",
		three_digit_ISO_country_code: "703",
	},
	{
		country: "Sierra Leone",
		image: "https://flagcdn.com/96x72/sl.png",
		ISOcode: "sl",
		three_digit_ISO_country_code: "694",
	},
	{
		country: "San Marino",
		image: "https://flagcdn.com/96x72/sm.png",
		ISOcode: "sm",
		three_digit_ISO_country_code: "674",
	},
	{
		country: "Senegal",
		image: "https://flagcdn.com/96x72/sn.png",
		ISOcode: "sn",
		three_digit_ISO_country_code: "686",
	},
	{
		country: "Somalia",
		image: "https://flagcdn.com/96x72/so.png",
		ISOcode: "so",
		three_digit_ISO_country_code: "706",
	},
	{
		country: "Suriname",
		image: "https://flagcdn.com/96x72/sr.png",
		ISOcode: "sr",
		three_digit_ISO_country_code: "740",
	},
	{
		country: "South Sudan",
		image: "https://flagcdn.com/96x72/ss.png",
		ISOcode: "ss",
		three_digit_ISO_country_code: "728",
	},
	{
		country:
			"S\u00c3\u0192\u00c2\u00a3o Tom\u00c3\u0192\u00c2\u00a9 and Pr\u00c3\u0192\\xadncipe",
		image: "https://flagcdn.com/96x72/st.png",
		ISOcode: "st",
		three_digit_ISO_country_code: "678",
	},
	{
		country: "El Salvador",
		image: "https://flagcdn.com/96x72/sv.png",
		ISOcode: "sv",
		three_digit_ISO_country_code: "222",
	},
	{
		country: "Sint Maarten",
		image: "https://flagcdn.com/96x72/sx.png",
		ISOcode: "sx",
		three_digit_ISO_country_code: "534"
	},
	{
		country: "Syria",
		image: "https://flagcdn.com/96x72/sy.png",
		ISOcode: "sy",
		three_digit_ISO_country_code: "760"
	},
	{
		country: "Eswatini (Swaziland)",
		image: "https://flagcdn.com/96x72/sz.png",
		ISOcode: "sz",
		three_digit_ISO_country_code: "748"
	},
	{
		country: "Turks and Caicos Islands",
		image: "https://flagcdn.com/96x72/tc.png",
		ISOcode: "tc",
		three_digit_ISO_country_code: "796",
	},
	{
		country: "Chad",
		image: "https://flagcdn.com/96x72/td.png",
		ISOcode: "td",
		three_digit_ISO_country_code: "148",
	},
	{
		country: "French Southern and Antarctic Lands",
		image: "https://flagcdn.com/96x72/tf.png",
		ISOcode: "tf",
		three_digit_ISO_country_code: "260",
	},
	{
		country: "Togo",
		image: "https://flagcdn.com/96x72/tg.png",
		ISOcode: "tg",
		three_digit_ISO_country_code: "768",
	},
	{
		country: "Thailand",
		image: "https://flagcdn.com/96x72/th.png",
		ISOcode: "th",
		three_digit_ISO_country_code: "764",
	},
	{
		country: "Tajikistan",
		image: "https://flagcdn.com/96x72/tj.png",
		ISOcode: "tj",
		three_digit_ISO_country_code: "762",
	},
	{
		country: "Tokelau",
		image: "https://flagcdn.com/96x72/tk.png",
		ISOcode: "tk",
		three_digit_ISO_country_code: "772",
	},
	{
		country: "Timor-Leste",
		image: "https://flagcdn.com/96x72/tl.png",
		ISOcode: "tl",
		three_digit_ISO_country_code: "626",
	},
	{
		country: "Turkmenistan",
		image: "https://flagcdn.com/96x72/tm.png",
		ISOcode: "tm",
		three_digit_ISO_country_code: "795",
	},
	{
		country: "Tunisia",
		image: "https://flagcdn.com/96x72/tn.png",
		ISOcode: "tn",
		three_digit_ISO_country_code: "788",
	},
	{
		country: "Tonga",
		image: "https://flagcdn.com/96x72/to.png",
		ISOcode: "to",
		three_digit_ISO_country_code: "776",
	},
	{
		country: "Turkey",
		image: "https://flagcdn.com/96x72/tr.png",
		ISOcode: "tr",
		three_digit_ISO_country_code: "792",
	},
	{
		country: "Trinidad and Tobago",
		image: "https://flagcdn.com/96x72/tt.png",
		ISOcode: "tt",
		three_digit_ISO_country_code: "780",
	},
	{
		country: "Tuvalu",
		image: "https://flagcdn.com/96x72/tv.png",
		ISOcode: "tv",
		three_digit_ISO_country_code: "798",
	},
	{
		country: "Taiwan",
		image: "https://flagcdn.com/96x72/tw.png",
		ISOcode: "tw",
		three_digit_ISO_country_code: "158",
	},
	{
		country: "Tanzania",
		image: "https://flagcdn.com/96x72/tz.png",
		ISOcode: "tz",
		three_digit_ISO_country_code: "834",
	},
	{
		country: "Ukraine",
		image: "https://flagcdn.com/96x72/ua.png",
		ISOcode: "ua",
		three_digit_ISO_country_code: "804",
	},
	{
		country: "Uganda",
		image: "https://flagcdn.com/96x72/ug.png",
		ISOcode: "ug",
		three_digit_ISO_country_code: "800",
	},
	{
		country: "United States Minor Outlying Islands",
		image: "https://flagcdn.com/96x72/um.png",
		ISOcode: "um",
		three_digit_ISO_country_code: "581",
	},
	{
		country: "United Nations",
		image: "https://flagcdn.com/96x72/un.png",
		ISOcode: "un",
	},
	{
		country: "United States",
		image: "https://flagcdn.com/96x72/us.png",
		ISOcode: "us",
		three_digit_ISO_country_code: "840",
	},
	{
		country: "Uruguay",
		image: "https://flagcdn.com/96x72/uy.png",
		ISOcode: "uy",
		three_digit_ISO_country_code: "858",
	},
	{
		country: "Uzbekistan",
		image: "https://flagcdn.com/96x72/uz.png",
		ISOcode: "uz",
		three_digit_ISO_country_code: "860",
	},
	{
		country: "Vatican City (Holy See)",
		image: "https://flagcdn.com/96x72/va.png",
		ISOcode: "va",
	},
	{
		country: "Saint Vincent and the Grenadines",
		image: "https://flagcdn.com/96x72/vc.png",
		ISOcode: "vc",
		three_digit_ISO_country_code: "670",
	},
	{
		country: "Venezuela",
		image: "https://flagcdn.com/96x72/ve.png",
		ISOcode: "ve",
		three_digit_ISO_country_code: "862",
	},
	{
		country: "British Virgin Islands",
		image: "https://flagcdn.com/96x72/vg.png",
		ISOcode: "vg",
		three_digit_ISO_country_code: "092",
	},
	{
		country: "United States Virgin Islands",
		image: "https://flagcdn.com/96x72/vi.png",
		ISOcode: "vi",
		three_digit_ISO_country_code: "850",
	},
	{
		country: "Vietnam",
		image: "https://flagcdn.com/96x72/vn.png",
		ISOcode: "vn",
		three_digit_ISO_country_code: "704",
	},
	{
		country: "Vanuatu",
		image: "https://flagcdn.com/96x72/vu.png",
		ISOcode: "vu",
		three_digit_ISO_country_code: "548",
	},
	{
		country: "Wallis and Futuna",
		image: "https://flagcdn.com/96x72/wf.png",
		ISOcode: "wf",
		three_digit_ISO_country_code: "876",
	},
	{
		country: "Samoa",
		image: "https://flagcdn.com/96x72/ws.png",
		ISOcode: "ws",
		three_digit_ISO_country_code: "882",
	},
	{
		country: "Kosovo",
		image: "https://flagcdn.com/96x72/xk.png",
		ISOcode: "xk",
	},
	{
		country: "Yemen",
		image: "https://flagcdn.com/96x72/ye.png",
		ISOcode: "ye",
		three_digit_ISO_country_code: "887",
	},
	{
		country: "Mayotte",
		image: "https://flagcdn.com/96x72/yt.png",
		ISOcode: "yt",
		three_digit_ISO_country_code: "175",
	},
	{
		country: "South Africa",
		image: "https://flagcdn.com/96x72/za.png",
		ISOcode: "za",
		three_digit_ISO_country_code: "710",
	},
	{
		country: "Zambia",
		image: "https://flagcdn.com/96x72/zm.png",
		ISOcode: "zm",
		three_digit_ISO_country_code: "894",
	},
	{
		country: "Zimbabwe",
		image: "https://flagcdn.com/96x72/zw.png",
		ISOcode: "zw",
		three_digit_ISO_country_code: "716",
	},
];
